### PR TITLE
fix comment for factory reset, should be /3/0/5

### PR DESCRIPTION
**Pull request by cvasilak**
[X] I confirm this contribution is my own and I agree to license it with Apache 2.0.
[X] I confirm the moderators may change the PR before merging it in.
[X] I understand the release model prohibits detailed Git history and my contribution will be recorded to the list at the bottom of [CONTRIBUTING.md](CONTRIBUTING.md).

### Summary of changes 

misleading comment for factory reset, should be '/3/0/5' instead of '/3/0/6'

### CODE REVIEW

**Comment by cvasilak** [comment]
@teetak01 mind to have a look ?

**Comment by teetak01** [comment]
Hi @cvasilak would you mind making the PR to mbed-cloud-client-example-internal?

No code-changes are accepted directly to the release repository.

**Comment by cvasilak** [comment]
@teetak01 opened internal PR.

**Comment by teetak01** [comment]
Closing. Part of upcoming 4.4.0 release.

**Pull request closed without merging**
